### ISSUE TITLE
Works right out of the box, but scaling is off by 10%

### ISSUE THREAD

**Issue by tliebig** [louisremi/background-size-polyfill#1]
Just added the code to http://www.insachenkunst.de/kuenstler/tom-schulhauser/, and it worked instantly in IE8. 

Just a hint: Scaling for 'contain' seems a little off - some 20-40 Pixels seem to be cut off at the top and bottom compared to browsers that support the poperty natively.

Great Job and a welcome successor to https://github.com/louisremi/jquery.backgroundSize.js

As always: If I can be of any helped zeroing in on the issue, let me know!

**Comment by louisremi** [comment]
Alright, I'll have a look at it asap.
Ping me if you don't here from me before the end of the week. I'm @louis_remi on twitter

**Comment by louisremi** [comment]
Hi @tliebig,

I just visited your website and I couldn't spot any difference between the latest Firefox and IE8. Did you do anything special?

**Comment by dBenitoSynergy** [comment]
Same issue here. It add space on top and bottom of the background.

**Comment by louisremi** [comment]
@dBentoSynergy same issue where, exactly? ;^)

**Comment by tliebig** [comment]
Hi @ louisremi,

no, nothing special. It's not off by much, either, but there is definitely a difference.

Screenshot: 
![ie8_vs_firefox](https://f.cloud.github.com/assets/216014/8710/ca0a4168-4481-11e2-8d44-527ac9849971.png)

Left half = IE10 in IE8 mode on Win7 via Virtualbox, Right side = current Firefox on Mac.

@dBentoSynergy:
Is this the same issue you're experiencing?

Yours,
Torsten

**Comment by louisremi** [comment]
@tliebig Oh alright, the height appears to be the same but the image is actually bigger but not entirely visible.
I'm going to investigate.

**Comment by louisremi** [comment]
@tliebig I'm not really sure of what is going on. Do you mind switching momentarily to the Github hosted version of the behavior? `-ms-behavior: url(http://louisremi.github.com/background-size-polyfill/backgroundsize.min.htc);`

**Comment by tliebig** [comment]
Okay, I just updated the code. Please not that although the page should not get a whole lot of traffic currently, it is still on the live server and should be left in a clean state after finishing the work - so please keep me updated. Thanks alot!

**Comment by louisremi** [comment]
Oh God, I just realized it isn't possible to load the behavior across domains... It means my documentation is wrong and the script is harder to use than I thought. I'm so sad :-(
You can revert back to the previous URL. I have to update the documentation before I can fix your problem.

**Comment by jefferyto** [comment]
@tliebig I just tried http://www.insachenkunst.de/kuenstler/tom-schulhauser/ and it looks like you're still linking to the GitHub-hosted version? As louisremi mentioned, it isn't possible to load behaviors across different domains (I get a JS error in IE8). It would help if you can load your local copy so that we can see the issue.

@dBentoSynergy Can you post a link?

**Comment by tliebig** [comment]
@jefferyto Updated the code so that the behavior should be loaded from the same domain. I don't have access to an IE8 installation anymore, so I cannot test the issue myself unfortunately. Since IE8 usage dropped below important levels in between, I'm not in dire need for a solution anymore.

I'd be glad to help you out debugging the issue, though. Should you need any other changes, please go ahead an just tell me what to change.

**Comment by jefferyto** [comment]
@tliebig Comparing your page between IE8 (Windows XP) and the current Firefox/Chrome (Ubuntu 13.04), I don't see any difference. I guess the issue has been fixed. (btw I wouldn't trust IE10 in IE8 mode)

**Comment by tliebig** [comment]
Okay, then I consider the issue fixed. Thanks for taking the time to look over it!

**Comment by jefferyto** [comment]
Thanks for restoring the behavior loading so I could test :-)
