### ISSUE TITLE
Dynamically setting background-image: none still displays image

### ISSUE THREAD

**Issue by gmcnaughton** [louisremi/background-size-polyfill#13]
If an element starts with `background-image: url(...)` but javascript later sets it to `background-image: none`, the original image still displays.

My workaround was to add `img.style.visibility = "hidden";` to ln 138 (in the else clause of refreshBackgroundImage, when the src cannot be parsed).

**Comment by jefferyto** [comment]
Thanks for submitting this! 0.2.0 should handle `background-image: none` set from JavaScript; please reopen (or file a new ticket) if you find it doesn't.
