### ISSUE TITLE
anchors over background-image on IE

### ISSUE THREAD

**Issue by ianwarn** [louisremi/background-size-polyfill#25]
I have absolutely positioned anchors, as child elements of a div with a background image. On IE8, the anchors are always underneath the div - so cannot be clicked, even when explicitly set with z-index.

**Comment by jefferyto** [comment]
Can you post a link?

**Comment by ianwarn** [comment]
http://aograduate.awaredesign.co.nz/what-we-offer/your-career-path/
Click on the headline 'I’m a law student' to reveal the infographic - compare it to non-IE browsers to see interaction.
I can accept that background-position rollovers probably won't work using this method, however as content is shown using the anchor link, it would be great if they were at least clickable.

**Comment by jefferyto** [comment]
I get a 404 when I open that page, can you check?

**Comment by ianwarn** [comment]
Sorry - in the middle of development. Page has moved to here: http://aograduate.awaredesign.co.nz/what-we-offer/your-route-to-qualification/

**Comment by jefferyto** [comment]
Try setting a transparent background image to the links. IE sometimes doesn't recognize clickable areas unless it has a background colour or image.

**Comment by ianwarn** [comment]
Perfect! Thanks, Jeffery for your quick and complete fix.
