### ISSUE TITLE
IE 8 error

### ISSUE THREAD

**Issue by ururk** [louisremi/background-size-polyfill#3]
I'm getting an error in IE 8:

Invalid argument. -> line 217

img.style.top = -delta + "px";

This doesn't always happen. I can see that an image has been drawn in the upper-left corner of my containing div. It isn't the image shrunk down - rather, it is an icon of a picture. Other times it works OK. Is there an issue if the image is large and hasn't finished loading? That really shouldn't be the case (I don't think) because the background image loads then flashes off.

**Comment by ururk** [comment]
It looks like the initial image scales/displays properly, but then the script continues to run. I'm trying to determine if there is something wrong with my code that prevents this form working correctly.

**Comment by ururk** [comment]
Fixed! It was a simple issue:

section .slides div{
}

This was evaluating for (what appeared) to be every div on the page, not just the targeted div.

**Comment by louisremi** [comment]
alright, closing this issue then.
