### ISSUE TITLE
Doesn't work for <img> tag

### ISSUE THREAD

**Issue by c0nstantine** [louisremi/background-size-polyfill#33]
Thanks for the great feature but it doesn't for <img> tag

e.g.
CSS:
    .splash {
        background: url(http://louisremi.github.io/background-size-polyfill/images/jar1.jpg) center no-repeat;
        -ms-behavior: url(/backgroundsize.min.htc);
        behavior: url(/backgroundsize.min.htc);
        background-size: cover;
    }
HTML:
        &lt;img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" width="960" height="400" class="splash" /&gt;

**Comment by louisremi** [comment]
This is working as intended. `<img>` tags aren't supposed to have a background image.
You should use a different tag :-)

**Comment by c0nstantine** [comment]
oh, thanks for the quick feedback Louis-Rémi! are there any hacks to patch it ?
thanks!!!

**Comment by louisremi** [comment]
As far as I know, no

**Comment by c0nstantine** [comment]
hm, but Chrome and FF support it and it looks like there is some way...
one more time thank you Louis-Rémi!
