### ISSUE TITLE
IE8: Original image below resized image

### ISSUE THREAD

**Issue by Awem** [louisremi/background-size-polyfill#35]
In my LESS-File (Joomla/Gantry4) I use BSP like this:

```
body #rt-logo {
    background: url(/images/logos/Logo.png) 50% 0 no-repeat !important;
    height: 150px;
    width: 150px;
    background-size: contain !important;
    -ms-behavior: url(/backgroundsize.min.htc);
}
```

In IE8 I can see the properly sized logo, but underneath it I can see the original logo, because the PNG file has transparent parts.

**Comment by jefferyto** [comment]
Is the original logo still visible if you remove `!important` from your `background` declaration?

**Comment by Awem** [comment]
Yes, removing `!important` fixes the issue. Is this the intended behavior?

**Comment by jefferyto** [comment]
It was, but I think I've found a way (after forgetting it earlier) to override `!important` styles. I'll see if I have time to work on this soon.

**Comment by Awem** [comment]
Your patch fixes the issue. Thanks a lot!

**Comment by jefferyto** [comment]
Great - thanks!
