### ISSUE TITLE
background-size with px

### ISSUE THREAD

**Issue by juliogc** [louisremi/background-size-polyfill#36]
Is this possible to use the polyfill with a predefined size, beyond 'cover' or 'contains' like:
# element {

```
background-size : 500px 200px
```

}

**Comment by jefferyto** [comment]
Yes it should work - give it a try! :smile:

**Comment by mrpritchett** [comment]
The background size will work on modern browsers, but the polyfill has to have cover or contain for ie8.

**Comment by jefferyto** [comment]
@mrpritchett The polyfill supports lengths (px, %, em, etc) in 0.2.0
