### ISSUE TITLE
Is doesnt work

### ISSUE THREAD

**Issue by ghost** [louisremi/background-size-polyfill#57]
Hi, youre pollifill doesnt work in ie8
![ie8](https://cloud.githubusercontent.com/assets/4718584/4668834/4f237506-5568-11e4-94a6-16fba4c05520.png)

**Comment by jefferyto** [comment]
Is this real IE8 or IE8 Compatibility View?

**Comment by jefferyto** [comment]
Or IE8 "Browser Mode"? Please re-test in real IE8.

**Comment by ghost** [comment]
it's not work in ie 10, in ie8 compatibility view
