### ISSUE TITLE
Changing dynamically  the background image with IE8 ?

### ISSUE THREAD

**Issue by sebcante** [louisremi/background-size-polyfill#7]
Hi louisremi,

Thanks for your work it pretty much worked out of the box!
Something i am wondering if there is a way to change dynamically the background image via CSS with IE8 and using the htc hook.
Let s say you have 2 skins where each of them have a different background images

```
<div class="skin1">
   <div class="elem> </div>
</div>

.skin1  .elem {
background-image: url(images/img1.jpg);
}
.skin2  .elem {
background-image: url(images/img2.jpg);
} 

.elem{
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
    -ms-behavior: url(backgroundsize.min.htc);
}
```

i managed to display the img1 ok in IE8 , but when i switch the skin css class from skin1 to skin2 the img2 does not showup as if the backgroundsize.min.htc executes once . Do you know if there is a way to reset it ? 

thanks

-seb

**Comment by techhead** [comment]
Seb,

I had this same issue.  After swapping out the class name on the element,
just change another watched property.

`elem.style.backgroundImage='';` worked for me.

**Comment by sebcante** [comment]
Thanks jonathan for your help
